# Logic of Inference Project - N Queens Problem

### Rakhya's Method Implementation 

Rakhya's Method is a case-based approach to the N-Queens Problem. The Solution reduces the processing time significantly as compared to several other algorithms like Backtracking. Numpy arrays are used for representation.

In [1]:
import numpy as np

This case-based approach involves decisions based on the value of n.

In [2]:
n = int(input("Mention N for which you would like to compute the problem: "))

Mention N for which you would like to compute the problem: 18


In [3]:
if n%2 != 0:
    print("The number is odd")
    if (n-3)%6 == 0:
        print("The case is yet to be decided")
        if ((n+1)/2)%2 == 0:
            case='F'
            print("The case is decided to be case F")
        else:
            case='E'
            print("The case is decided to be case E")
    else:
        case='B'
        print("The case is decided to be case B")
else:
    print("The number is even")
    if (n-2)%6 == 0:
        print("The case is yet to be decided")
        if (n/2)%2 == 0:
            case='C'
            print("The case is decided to be case C")
        else:
            case='D'
            print("The case is decided to be case D")
    else:
        case='A'
        print("The case is decided to be case A")

The number is even
The case is decided to be case A


## Case-based Analogy and approach to each case

Detailed Explanation

In [5]:
arr = np.zeros((n,n) , dtype=int)

if case=='A':
    print("A")
    for i in range(n):
        if i%2 != 0 :
            arr[i][(i-1)//2]=1
        else:
            arr[i][(i+n)//2]=1
elif case=='B':
    print("B")
    for i in range(n):
        if i%2 != 0 :
            arr[i][(i+n)//2]=1
        else:
            arr[i][(i)//2]=1

elif case=='C':
    print("C")
    for i in range(n):
        if i%2 != 0 :
            arr[i][(i-1)//2]=1
        else:
            if i%4 == 0:
                arr[i][(i+n+2)//2]=1
            else:
                arr[i][(i+n-2)//2]=1

elif case=='D':
    print("D")
    arr[n-2][0]=1
    for i in range(n):
        if i%2 != 0 :
            arr[i][(i+1)//2]=1
        else:
            if i%4 == 0 and i<=n-6:
                arr[i][(i+n+4)//2]=1
            elif i%4 != 0 and i<=n-4:
                arr[i][(i+n)//2]=1

elif case=='E':
    print("E")
    arr[n-2][0]=1
    arr[n-4][1]=1
    for i in range(n):
        if i%2 == 0 :
            arr[i][(i+4)//2]=1
        else:
            if (i-3)%4 == 0 and i<=n-6:
                arr[i][(i+n+2)//2]=1
            elif (i-1)%4 == 0 and i<=n-8:
                arr[i][(i+n+6)//2]=1

    
elif case=='F':
    print("F")
    arr[0][n-1]=1
    arr[2][n-2]=1
    for i in range(n):
        if i%2 != 0 and i<=n-2:
            arr[i][(i+n-4)//2]=1
        else:
            if i%4 == 0 and i<=n-3:
                arr[i][(i-2)//2]=1
            elif (i-2)%4 == 0 :
                arr[i][(i-6)//2]=1

    
print(arr)

A
[[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]]
